NethServer/nethsecurity-ui

- src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
- src/components/standalone/interfaces_and_devices/UnconfigureDeviceModal.vue
- src/lib/standalone/network.ts
- src/views/standalone/network/InterfacesAndDevicesView.vue
Fixes to **Network > Interfaces and devices** page:
- fix interface configuration removal
- various fixes on bridges and bonds
- fix duplicated IP addresses
- improve ipv6 management
> Logical interfaces fixes

- package-lock.json
- package.json
- public/i18n/en/translation.json
- src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
- src/components/standalone/interfaces_and_devices/CreateVlanDeviceDrawer.vue
- src/lib/standalone/network.ts
- src/views/standalone/network/InterfacesAndDevicesView.vue
While creating a logical device, in some cases the list of available devices for the bridge/bond was not properly populated
> Fix bridge/bond devices list

- src/components/standalone/interfaces_and_devices/CreateOrEditAliasInterfaceDrawer.vue
- src/lib/standalone/network.ts
- src/views/standalone/network/InterfacesAndDevicesView.vue
- Fix retrieval of interfaces data
- Fix bond visualization
- Shorten default alias name
> Fix interfaces data visualization

- src/views/standalone/network/InterfacesAndDevicesView.vue
> fix(sa/devices): add null-check on device link

- src/views/standalone/network/InterfacesAndDevicesView.vue
Fix: show MAC address for VLAN devices
> Interfaces: show MAC for VLANs

- public/i18n/en/translation.json
- src/components/standalone/dashboard/RealTimeTrafficCard.vue
- src/components/standalone/dashboard/ServiceCard.vue
- src/components/standalone/dashboard/SystemInfoCard.vue
- src/components/standalone/dashboard/TrafficSummaryChart.vue
- src/components/standalone/dashboard/WanTrafficCard.vue
- src/components/standalone/dashboard/WanTrafficChart.vue
- src/composables/useTrafficSummary.ts
- src/lib/color.ts
- src/views/standalone/StandaloneDashboardView.vue
- src/views/standalone/network/InterfacesAndDevicesView.vue
- Add OpenVPN RW card
- Fix color of charts grid
- Show legend in WAN traffic chart
- Fix values in real time traffic chart
- Show data refresh interval
- Enhance memory/storage info
> Fix dashboard cards

- src/components/standalone/dashboard/RealTimeTrafficCard.vue
> fix(dashboard): fix number format

- src/StandaloneApp.vue
- src/stores/standalone/standaloneLogin.ts
Authentication token is automatically refreshed once in a while, if the user keeps using the webapp.
Refreshing means that a new token is stored and used.
Anytime the user makes a request to the api-server, the token is refreshed if at least half an hour has passed since last refresh.
> Refresh authentication token

- package-lock.json
- package.json
- src/assets/main.css
- src/main.ts
- Install and configure [vue-tippy](https://github.com/KABBOUCHI/vue-tippy)
- Update `@nethserver/vue-tailwind-lib` to get tooltip support on various components
See https://github.com/NethServer/vue-tailwind-lib/pull/10
> Tooltips support

- src/components/standalone/multi-wan/PolicyCreator.vue
- src/components/standalone/multi-wan/PolicyEditor.vue
- src/composables/usePolicyForm.ts
Due to an unknown issue with post processor, `.push(new Gateway())` was being translated in to `.push(new unref(Gateway()))` that caused issues while running in the final build.
> fix(mwan): fix gateway/priority creation

- src/composables/useTabs.ts
- src/views/standalone/network/RoutesView.vue
- src/views/standalone/system/SystemSettingsView.vue
Updated handling of tabs in different pages, fixed "backbutton" behaviour
> fix: fixed issue where router history wasn't honored

- public/i18n/en/translation.json
- src/components/standalone/security/FlashstartContent.vue
- Clear errors
- Zone select
- Valid bypass source
> fix: flashstart page

- public/i18n/en/translation.json
- src/components/standalone/hotspot/SettingsContent.vue
> Hotspot page

- src/ControllerApp.vue
- src/StandaloneApp.vue
- src/lib/i18n.ts
Fix English fallback while loading i18n strings
> fix: loading of unsupported language

- public/i18n/en/translation.json
- src/views/standalone/StandaloneDashboardView.vue
Add hotspot status card to Dashboard page
> feat: hotspot card

- public/i18n/en/translation.json
> fix: ipsec, replace label placeholders

- public/i18n/en/translation.json
- src/components/standalone/report/PingContent.vue
- src/components/standalone/report/ReportContent.vue
- src/lib/fontawesome.ts
- src/router/index.ts
- src/views/standalone/ReportView.vue
Netdata proxypass has been removed so the API has been simplified.
The link on the first tab is now hard-coded.
Replaces https://github.com/NethServer/nethsecurity-ui/pull/76
Card: https://trello.com/c/oNd1oPPW/134-ping-latency-monitor
See also https://github.com/NethServer/nethsecurity/pull/221
> Report page

- public/i18n/en/translation.json
- src/components/standalone/SideMenu.vue
- src/components/standalone/factory_reset/FactoryResetContent.vue
- src/lib/fontawesome.ts
- src/router/index.ts
- src/views/standalone/system/FactoryResetView.vue
Add Factory reset page
See also https://github.com/NethServer/nethsecurity/pull/219
> feat: factory reset

- src/components/standalone/hotspot/SettingsContent.vue
Fixes the following problems:
- remote parameters are now disabled after the unit has been registered
- the interface was always set to the first available one
> Hotspot fixes

- src/components/standalone/NeMultiTextInput.vue
- src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
- src/components/standalone/firewall/DeletePortForwardModal.vue
- src/views/standalone/firewall/PortForward.vue
- Fix error with hairpin nat zones combobox
- Include error details in notifications for port forward page
- Minor code cleanup
Card: https://trello.com/c/BroPx8ow/235-port-forward-hairpin-nat-error
> Port forward: fix hairpin nat zones combobox, include error details

- public/i18n/en/translation.json
- src/components/standalone/hotspot/StatusContent.vue
> feat: hotspot, mark temporary sessions

- public/i18n/en/translation.json
Updates are not still automated.
> fix: updates, change main label

- .eslintrc.cjs
- src/components/standalone/backup_and_restore/BackupContent.vue
- src/components/standalone/backup_and_restore/ModalDownloadBackup.vue
- src/components/standalone/backup_and_restore/RestoreContent.vue
- src/components/standalone/dns_dhcp/CreateOrEditDnsRecordDrawer.vue
- src/components/standalone/dns_dhcp/CreateOrEditStaticLeaseDrawer.vue
- src/components/standalone/dpi/CreateOrDeleteDpiExceptionDrawer.vue
- src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
- src/components/standalone/hotspot/SettingsContent.vue
- src/components/standalone/hotspot/StatusContent.vue
- src/components/standalone/ipsec_tunnel/CreateOrEditTunnelDrawer.vue
- src/components/standalone/reverse_proxy/CreateOrEditProxyDrawer.vue
- src/components/standalone/routes/CreateOrEditRouteDrawer.vue
- src/components/standalone/routes/RoutesContent.vue
- src/components/standalone/security/FlashstartContent.vue
- src/components/standalone/subscription/UnitSubscription.vue
- src/components/standalone/update/ScheduleUpdateDrawer.vue
- src/components/standalone/users_database/CreateOrEditDatabaseDrawer.vue
- src/composables/useTimer.ts
- src/lib/validation.ts
- src/views/standalone/system/UpdateView.vue
Force use of curly braces was missing from the eslint style format, it's added and I've already formatted the files accordingly.
~~It's probably better to wait for #108, then rebase and fix the additional files.~~
> style: forced curlies to eslint

- src/lib/i18n.ts
- src/main.ts
Show English strings on the UI as a fallback for missing i18n strings
> feat: fallback i18n to english for missing strings

- public/i18n/en/translation.json
- src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
Card: https://trello.com/c/ERifUajb/215-openvpn-strong-weak-ciphers-and-digest
> feat: ovpn tunnel show strong/weak label for ciphers

- public/i18n/en/translation.json
- src/components/standalone/update/SystemUpdateInProgressModal.vue
- src/components/standalone/update/UpdatePackagesModal.vue
- src/lib/standalone/network.ts
- src/stores/standalone/firewall.ts
- src/views/standalone/vpn/OpenvpnRoadWarriorView.vue
Fix icon and colors of RWOPENVPN zone
Other changes:
- Extend wait time of system update: sometimes the page is automatically refreshed before the system is
fully rebooted and the the webapp is restarted
- Improve OVPN RW skeleton
- Fix i18n strings in Updates page
> fix: style of rwopenvpn zone

- public/i18n/en/translation.json
- src/lib/standalone/network.ts
- src/views/standalone/network/InterfacesAndDevicesView.vue
List OpenVPN Road Warrior servers in **Interfaces and devices** page
> fix: show openvpn rw servers in devices page

- public/i18n/en/translation.json
Some improvements in the openvpn rw section
> Added some information and improvements in openvpn rw

- public/i18n/en/translation.json
add remote address -> add remote network
> more clear label on openvpn server config

- public/i18n/en/translation.json
- src/components/standalone/dns_dhcp/DnsManager.vue
- src/lib/validation.ts
- Add specific validation function for DNS forwarding servers, following the same specs used by LuCI
Card: https://trello.com/c/dyu6tLPV/273-dns-relax-validator-for-dns-forwarding-servers
> DNS: add specific validation for DNS forwarding servers

- public/i18n/en/translation.json
Card: https://trello.com/c/79bj4dW5/275-dns-change-behaviour-of-dns-domain-option
> fix: improve dns domain tooltip

- src/stores/standalone/uciPendingChanges.ts
See https://github.com/NethServer/nethsecurity/pull/295
> refactor: uci changes, use ns.commit API

- public/i18n/en/translation.json
- src/StandaloneApp.vue
- src/components/standalone/backup_and_restore/MigrationDrawer.vue
- Update migration in progress translation to inform the users of the IPs through which the machine will be reachable
- Rework migration in progress timer using the `useTimer` composable
- Minor migration drawer ui fixes (reset the form when the drawer is reoponed, avoid closing migration in progress modal)
- Avoid showing axios error toast when the migration call fails, even if successful
Card: https://trello.com/c/T27Pn7IP/294-improve-migration-ui
> Migration: apply various UI enhancements

- public/i18n/en/translation.json
- src/views/standalone/system/UpdateView.vue
- Add automatic updates in Update page
Card: https://trello.com/c/MZFXHT8w/289-enable-automatic-updates-checkbox-for-subscribers
> Update: add automatic updates

- package-lock.json
- package.json
- src/components/standalone/AxiosErrorModal.vue
- src/components/standalone/NeAxiosErrorModal.vue
- src/components/standalone/account/two_fa/TwoFactorAuth.vue
- src/components/standalone/backup_and_restore/MigrationDrawer.vue
- src/components/standalone/backup_and_restore/RestoreContent.vue
- src/components/standalone/certificates/CreateLetsEncryptCertificateDrawer.vue
- src/components/standalone/certificates/ImportCertificateDrawer.vue
- src/components/standalone/dpi/CreateOrDeleteDpiExceptionDrawer.vue
- src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
- src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
- src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue
- src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
- src/components/standalone/interfaces_and_devices/CreateVlanDeviceDrawer.vue
- src/components/standalone/ipsec_tunnel/CreateOrEditTunnelDrawer.vue
- src/components/standalone/multi-wan/MultiWanGeneralSettings.vue
- src/components/standalone/multi-wan/PolicyCreator.vue
- src/components/standalone/multi-wan/PolicyEditor.vue
- src/components/standalone/openvpn_rw/CreateOrEditRWAccountDrawer.vue
- src/components/standalone/openvpn_rw/CreateOrEditRWServerDrawer.vue
- src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
- src/components/standalone/openvpn_tunnel/DownloadTunnelModal.vue
- src/components/standalone/qos/CreateOrEditQoSInterfaceDrawer.vue
- src/components/standalone/reverse_proxy/CreateOrEditProxyDrawer.vue
- src/components/standalone/security/FlashstartContent.vue
- src/components/standalone/system_settings/GeneralSettings.vue
- src/components/standalone/update/ScheduleUpdateDrawer.vue
- src/components/standalone/users_database/CreateOrEditDatabaseDrawer.vue
- src/views/standalone/system/StorageView.vue
Import `NeFormItemLabel` and `NeRadioSelection` from `vue-components`.
See:
- https://github.com/nethesis/vue-components/pull/16
> Import NeFormItemLabel & NeRadioSelection from vue-components

- src/components/standalone/firewall/rules/FirewallRulesTable.vue
Fix firewall rules management on any protocol
See:
- https://github.com/NethServer/python3-nethsec/pull/33
Card:
- https://trello.com/c/ggpLSzJ1/318-firewall-all-protocols-rule
> fix: fix fw rules on any protocol

- public/i18n/en/translation.json
- src/components/standalone/multi-wan/MultiWanManager.vue
- src/composables/useRuleForm.ts
- src/lib/validation.ts
- Allow for ipv4 usage in source/dest address when creating or editing a rule, with or without CIDR notation
- Disable delete option in policies used in rules
Card: https://trello.com/c/BzVku7eq/312-multiwan-various
> MultiWAN: minor ui improvements

- public/i18n/en/translation.json
- src/components/standalone/hotspot/StatusContent.vue
- src/views/standalone/network/HotspotView.vue
- Add badge to inform user of the hotspot configuration's status in the status tab
- Minor UI changes, simplify hotspot page structure
Card: https://trello.com/c/H6d0PGHA/169-hotspot-add-service-status-information
> Hotspot: add badge to inform user of the hotspot configuration's status

- public/i18n/en/translation.json
- src/components/standalone/firewall/nat/CreateOrEditNetmapRuleDrawer.vue
- src/components/standalone/firewall/nat/DeleteNetmapModal.vue
- src/components/standalone/firewall/nat/NatRulesContent.vue
- src/components/standalone/firewall/nat/NetmapContent.vue
- src/components/standalone/firewall/nat/NetmapTable.vue
- src/stores/standalone/firewall.ts
- src/views/standalone/firewall/NatView.vue
Add NETMAP section to NAT page
Card: https://trello.com/c/aSCKhOGD/332-netmap-ui
> feat: add netmap rules

- public/i18n/en/translation.json
- src/components/standalone/StandaloneAppShell.vue
- src/stores/standalone/notifications.ts
Briefly shake bell icon in the top bar when a new notification is received. This should help the user to discover the notification drawer.
Other changes:
- Add tooltips to top bar buttons
> feat: shake notification icon on new notifications

- public/i18n/en/translation.json
- src/views/standalone/system/CertificatesView.vue
Ref: NethServer/nethsecurity#353
> fix: updating certificate ui with latest backend changes

- public/i18n/en/translation.json
Card: https://trello.com/c/94ZKwwjY/339-acmesh-lets-encrypt-certificate-request-failed
> fix: improve labels for LE certificates

- src/components/controller/ControllerAppLogin.vue
- src/components/standalone/StandaloneAppLogin.vue
- src/components/standalone/account/two_fa/ConfigureTwoFaDrawer.vue
- src/components/standalone/account/two_fa/RevokeTwoFaModal.vue
- src/components/standalone/backup_and_restore/RestoreContent.vue
- src/components/standalone/dpi/ManageDpiRuleModal.vue
- src/components/standalone/firewall/nat/CreateOrEditNatRuleDrawer.vue
- src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue
- src/components/standalone/hotspot/SettingsContent.vue
- src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
- src/components/standalone/interfaces_and_devices/CreateOrEditAliasInterfaceDrawer.vue
- src/components/standalone/interfaces_and_devices/CreateVlanDeviceDrawer.vue
- src/components/standalone/routes/CreateOrEditRouteDrawer.vue
- src/components/standalone/security/FlashstartContent.vue
- src/components/standalone/ssh/SshKeys.vue
- src/components/standalone/subscription/UnitSubscription.vue
- src/components/standalone/system_settings/GeneralSettings.vue
Import `focusElement` and other functions from `vue-components` library
Other changes:
- DPI: fix warning in console `Invalid prop: type check failed for prop "ruleToEdit"`
> chore: import focusElement from vue-components

- public/i18n/it/translation.json
I propose to change "ripristino completo impostazioni di fabbrica" with  " factory default"
it takes up less space on the page and is now a common term even in the Italian language
> change  "ripristino di fabbrica" to "factory default"

- public/i18n/en/translation.json
- public/i18n/it/translation.json
- src/lib/standalone/network.ts
- src/stores/standalone/firewall.ts
The correct name is guest, in singular form.
> chore: rename guests zone to guest

- src/stores/controller/unitManagement.ts
- src/views/controller/ControllerDashboardView.vue
Show unit_id instead of unit_name.
See related PR: https://github.com/NethServer/nethsecurity-controller/pull/10
> fix: controller, use unit_id for registration

- src/ControllerApp.vue
- src/stores/controller/controllerLogin.ts
Fix invocation of `defaults` API
> fix(controller): fix defaults loading

- .env.production
- public/i18n/en/translation.json
- src/ControllerApp.vue
- src/stores/controller/controllerLogin.ts
- src/views/controller/UnitTerminalView.vue
- Call GET defaults API in UnitTerminalView
- Fix webSocket connection URL
- Remove useless code
> fix(controller): fix websocket connection url

- src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue
Firewall rules: allow IP range in destination addresses
> fix: allow IP range in destination of firewall rule

- public/i18n/en/translation.json
- src/StandaloneApp.vue
- src/components/controller/units/OpenSshModal.vue
- src/components/controller/units/UnitsTable.vue
- src/lib/config.ts
- src/lib/controller/sshKeys.ts
- src/lib/router.ts
- src/lib/standalone/ubus.ts
- src/stores/controller/units.ts
- src/views/standalone/StandaloneDashboardView.vue
- Open SSH terminal: retrieve unit SSH port
- Refactor ubus calls on units from the controller
> feat(controller): retrieve SSH port from unit

- public/i18n/en/translation.json
- src/components/controller/SideMenu.vue
- src/components/controller/users/CreateOrEditUserDrawer.vue
- src/components/controller/users/DeleteUserModal.vue
- src/components/controller/users/UsersTable.vue
- src/router/index.ts
- src/stores/controller/accounts.ts
- src/stores/controller/controllerLogin.ts
- src/views/controller/UsersView.vue
- Add users management page for controller
> Controller: add users page

- public/branding.js
> fix: branding, change product and docs URLs

- package-lock.json
- package.json
- src/components/standalone/users_database/CreateOrEditDatabaseDrawer.vue
- src/composables/useTabs.ts
- src/views/standalone/ReportView.vue
- src/views/standalone/firewall/FirewallRulesView.vue
- src/views/standalone/network/DnsDhcpView.vue
- src/views/standalone/network/HotspotView.vue
- src/views/standalone/network/MultiWanView.vue
- src/views/standalone/network/RoutesView.vue
- src/views/standalone/security/DpiFilterView.vue
- src/views/standalone/security/ThreatShieldView.vue
- src/views/standalone/system/BackupAndRestoreView.vue
- src/views/standalone/system/SystemSettingsView.vue
- src/views/standalone/vpn/OpenvpnTunnelView.vue
- src/views/standalone/vpn/UsersDatabaseView.vue
Import NeTabs component from vue-components
> chore: import NeTabs from vue-components

- src/ControllerApp.vue
- src/StandaloneApp.vue
- src/stores/controller/controllerLogin.ts
- src/stores/controller/units.ts
- src/stores/notifications.ts
- src/stores/standalone/standaloneLogin.ts
- Open unit: handle expiration and refresh of unit token
- Refresh token of controller user every 30 mins
> Controller: handle expiration and refresh of units token

- public/i18n/en/translation.json
- src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
Port forward: improve i18n string
See:
- https://github.com/NethServer/nethsecurity/issues/457
> fix: improve i18n string in Port forward page

- public/i18n/en/translation.json
- src/components/standalone/openvpn_rw/RWServerDetails.vue
- src/components/standalone/openvpn_tunnel/TunnelManager.vue
- src/views/standalone/vpn/IPsecTunnelView.vue
- src/views/standalone/vpn/OpenvpnRoadWarriorView.vue
- src/views/standalone/vpn/OpenvpnTunnelView.vue
Automatically reload data inside VPN pages every 10 seconds:
- OpenVPN Road Warrior
- OpenVPN tunnel
- IPsec tunnel
> Autoreload VPN pages

- public/i18n/en/translation.json
- src/components/standalone/routes/CreateOrEditRouteDrawer.vue
- src/components/standalone/routes/RoutesContent.vue
- src/lib/fontawesome.ts
- Prevent modification and deletion of readonly routes (e.g. routes created by IPsec tunnel)
- Set **Gateway** field as optional
- Remove default value for **Network address** and **Gateway**
- UI fixes
See:
- https://github.com/NethServer/nethsecurity/issues/450
- https://github.com/NethServer/nethsecurity/issues/452
> Various fixes on Routes page

- public/i18n/en/translation.json
blob message changed to cover missing  gateway option
https://github.com/NethServer/nethsecurity/issues/452
> route add blob gateway updated

- public/i18n/en/translation.json
- src/components/standalone/dns_dhcp/EditDhcpInterfaceDrawer.vue
See:
- https://github.com/NethServer/nethsecurity/issues/454
- https://github.com/NethServer/nethsecurity/pull/463
Screenshots:
> feat: dhcp, expose force option

- public/i18n/en/translation.json
- src/components/standalone/ipsec_tunnel/CreateOrEditTunnelDrawer.vue
https://github.com/NethServer/nethsecurity/issues/465
> fix: validation of local/remote ipsec networks

- public/i18n/en/translation.json
- src/components/standalone/subscription/CancelSubscriptionModal.vue
- src/components/standalone/subscription/UnitSubscription.vue
https://github.com/NethServer/nethsecurity/issues/475
> fix: confirm subscription cancellation

- src/components/standalone/dashboard/SystemInfoCard.vue
https://github.com/NethServer/nethsecurity/issues/478
> feat: show update available in system card

- src/components/standalone/NeTable.vue
- src/components/standalone/firewall/rules/FirewallRulesTable.vue
- src/components/standalone/firewall/rules/SourceOrDestinationRuleColumn.vue
- Change background color of disabled rules
- Show gray (`secondary`) badges for disabled rules
- Fix position of Edit and kebab buttons
- Fix standard background color of NeTable row for light theme
https://github.com/NethServer/nethsecurity/issues/480
> fix: style of disabled firewall rules

- src/components/standalone/multi-wan/MultiWanGeneralSettings.vue
Due to changes coming from https://github.com/NethServer/nethsecurity/pull/482, APIs have been updated.
> refactor(mwan): updated ubusCalls for new mwan api

- src/components/standalone/firewall/rules/FirewallRulesTable.vue
https://github.com/NethServer/nethsecurity/issues/487
> fix: vertical spacing of firewall rules

- src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
https://github.com/NethServer/nethsecurity/issues/488
> fix: don't show "Traffic to WAN" for WAN zone

- src/views/standalone/ReportView.vue
- src/views/standalone/network/HotspotView.vue
Fix tab navigation on **Report** and  **Hotspot** pages
> fix: navigation on pages using tabs

- package-lock.json
- package.json
- src/views/standalone/firewall/ZonesAndPolicies.vue
Zones & policies: Import NeTable component from vue-components
> refactor: import zones table from vue-components

- package-lock.json
- package.json
- public/i18n/en/translation.json
- src/lib/standalone/network.ts
- src/views/controller/UnitManagerView.vue
- src/views/standalone/network/InterfacesAndDevicesView.vue
https://github.com/NethServer/nethsecurity/issues/506
> fix: show vpn networks in Interfaces page

- .devcontainer/devcontainer.json
- package-lock.json
- package.json
- public/i18n/en/translation.json
- src/components/standalone/dashboard/OpenVpnTunnelOrIpsecCard.vue
- src/components/standalone/dashboard/ServiceCard.vue
- src/views/standalone/StandaloneDashboardView.vue
- https://github.com/NethServer/nethsecurity/issues/515
- https://github.com/NethServer/nethsecurity/issues/517
Other changes:
- Remove deprecated VS Code extensions from `devcontainer.json`
> fix: add service counters in Dashboard page

- src/components/standalone/dashboard/OpenVpnTunnelOrIpsecCard.vue
- src/components/standalone/dashboard/RealTimeTrafficCard.vue
- src/components/standalone/dashboard/ServiceCard.vue
- src/components/standalone/dashboard/SystemInfoCard.vue
- src/components/standalone/dashboard/WanTrafficCard.vue
- src/composables/useTrafficSummary.ts
Slow down to 20-30 seconds the update interval of dashboard cards
> fix: slow down update interval of dashboard

- src/views/standalone/network/InterfacesAndDevicesView.vue
https://github.com/NethServer/nethsecurity/issues/506
> fix: add ipsec tunnel name in Interfaces page

- public/i18n/en/translation.json
- src/ControllerApp.vue
- src/StandaloneApp.vue
- src/components/controller/ControllerAppLogin.vue
- src/components/controller/units/UnitsTable.vue
- src/components/controller/users/UsersTable.vue
- src/components/standalone/StandaloneAppLogin.vue
- src/components/standalone/dashboard/OpenVpnTunnelOrIpsecCard.vue
- src/stores/controller/controllerLogin.ts
- src/stores/standalone/standaloneLogin.ts
- src/views/controller/UnitManagerView.vue
- src/views/controller/UsersView.vue
- src/views/standalone/StandaloneDashboardView.vue
- src/views/standalone/firewall/ZonesAndPolicies.vue
- src/views/standalone/network/InterfacesAndDevicesView.vue
- Controller units: import NeTable from vue-components
- Controller users: import NeTable from vue-components
- Login page: show "Session has expired" when logging out because of token expiration
- Zones and policies: minor fixes
- Dashboard: fix update interval shown at the top of the page
- Replace "&" with "and" in i18n strings
- Clean up code
> refactor: import new NeTable and other enhancements

- src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
https://github.com/NethServer/nethsecurity/issues/533
> Show zone names in uppercase and save them in lowercase

- public/i18n/en/translation.json
- src/components/standalone/routes/RoutesContent.vue
Routes page: import tables from vue-components & minor fixes
> refactor: import routes table from vue-components

- package-lock.json
- package.json
- public/i18n/en/translation.json
- src/components/controller/units/UnitsTable.vue
- src/components/controller/users/UsersTable.vue
- src/components/standalone/NeTable.vue
- src/components/standalone/backup_and_restore/BackupContent.vue
- src/components/standalone/dns_dhcp/ScanResultsTable.vue
- src/components/standalone/routes/RoutesContent.vue
- src/components/standalone/security/threat_shield/BlocklistTable.vue
- src/components/standalone/users_database/UsersTable.vue
- src/lib/fontawesome.ts
- src/views/standalone/firewall/ZonesAndPolicies.vue
Refactor NeTables in order to use the improved NePaginator component
Other changes:
- Zones and policies: remove useless column "Covered networks"
> refactor: use improved NeTable pagination

- src/components/standalone/users_database/CreateOrEditUserDrawer.vue
https://github.com/NethServer/nethsecurity/issues/553
> fix: trim username while creating a user in local database

- package-lock.json
- package.json
> chore: upgrade to vue 3.4

- public/i18n/en/translation.json
- src/components/standalone/multi-wan/PolicyCreator.vue
- src/components/standalone/multi-wan/RuleCreator.vue
Add the translation for the maximal length for multiwan name 
NethServer/nethsecurity#556
> Add maximal length for mwan

- src/components/standalone/multi-wan/PolicyCreator.vue
- src/components/standalone/multi-wan/PolicyEditor.vue
- src/components/standalone/multi-wan/RuleCreator.vue
- src/components/standalone/multi-wan/RuleEditor.vue
- src/composables/useRuleForm.ts
This pull request refactors the form validation for the multi-wan policy/rule creator and editor components. 
It improves the validation logic and error messages for fields such as name, interfaces, source address, destination address, source port, and destination port. 
NethServer/nethsecurity#580
> Refactor form validation for multi-wan policy creator and editor

- public/i18n/en/translation.json
- src/components/standalone/users_database/CreateOrEditUserDrawer.vue
- src/components/standalone/users_database/UsersDatabaseManager.vue
- src/components/standalone/users_database/UsersTable.vue
- src/lib/fontawesome.ts
This pull request refactors the user administration features in the codebase. It includes the following changes:
- Added an administrator user tooltip to the translation.json file.
- Added an admin toggle to the CreateOrEditUserDrawer.vue file.
- Added an admin flag to the User type in the UsersDatabaseManager.vue file.
- Added remove_admin and set_admin function in the table (accessible from the dropdown
> Refactor user administration features

- public/i18n/en/translation.json
- src/components/standalone/users_database/CreateOrEditDatabaseDrawer.vue
> feat(users): add user_bind_dn field

- src/components/standalone/users_database/CreateOrEditDatabaseDrawer.vue
Remove suggestion of LDAP attributes based on LDAP URI (`get-ldap-defaults` api call) while creating a user database.
It looks like this kind of suggestions provides more harm than advantages.
> fix: remove suggestion of LDAP attributes

- public/i18n/en/translation.json
Display a better suggestion which should march Microsoft Active Directory installations.
> fix(users): improve user_attribute_tooltip

- public/i18n/en/translation.json
updated tooltip for custom user bind dn
> Custom user bind dn tooltip

- public/i18n/en/translation.json
- src/components/controller/units/UnitsTable.vue
- src/stores/controller/units.ts
- src/views/controller/UnitManagerView.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/638
> fix(controller): solve multi unit issues with continuos sync

- src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/650
> fix(interfaces): updating maxLen due to recent mwan issues

- src/components/standalone/backup_and_restore/BackupContent.vue
- src/components/standalone/backup_and_restore/RestoreContent.vue
- src/views/standalone/system/UpdateView.vue
- src/views/standalone/users_objects/UsersDatabaseView.vue
Display remote backup only for Enterprise subscription: Community subscription has no access to remote server yet
NethServer/nethsecurity#653
Requires https://github.com/NethServer/nethsecurity/pull/654
> fix(backup): fix remote backups list

- public/i18n/en/translation.json
Ref:
- https://github.com/NethServer/nethsecurity/issues/643
> fix(lang): adding new translation for already requested certificate

- public/i18n/en/translation.json
- src/components/standalone/backup_and_restore/BackupContent.vue
- src/components/standalone/backup_and_restore/ModalDeleteBackup.vue
- src/components/standalone/backup_and_restore/RestoreContent.vue
Now both Enterprise and Community subscriptions have access to the remote backup.
Requires: https://github.com/NethServer/nethsecurity/pull/652
Exposed also some more info:
- creation date in local time
- encrypted/not encrypted flag
- size
Also exposed the delete backup button.
Backup list:
Restore list:
Delete confirmation:
NethServer/nethsecurity#664
> feat(backup): remote backup for all subscriptions

- public/i18n/en/translation.json
- src/components/standalone/backup_and_restore/BackupContent.vue
- src/components/standalone/backup_and_restore/ModalDownloadBackup.vue
- src/components/standalone/backup_and_restore/SetPassphraseDrawer.vue
- If subscription is valid, set download extension based on mimetype
- Display a badge if passhprase is set
- Add passphrase placeholder
NethServer/nethsecurity#664
> Backup improvements

- src/components/standalone/backup_and_restore/BackupContent.vue
- src/components/standalone/backup_and_restore/ModalDownloadBackup.vue
Downloaded file has now a unique name like
`backup-<hostname>-<creation_timestamp>.<extension>`
Example: backup-NethSec-1721802072.tar.gz
> feat(backup): change backup downloaded file name

- .devcontainer/devcontainer.json
- src/components/DeleteModal.vue
- src/components/standalone/firewall/rules/SourceOrDestinationRuleColumn.vue
See:
- https://github.com/NethServer/nethsecurity/issues/677
Other changes:
- Add vscode extension to devcontainer
- Fix typo in comment
> fix: always show zone in firewall rules (if not "Any")

- public/i18n/en/translation.json
- src/components/standalone/firewall/rules/SourceOrDestinationRuleColumn.vue
- src/components/standalone/multi-wan/RuleCreator.vue
- src/components/standalone/multi-wan/RuleEditor.vue
- src/components/standalone/multi-wan/RuleManager.vue
- src/components/standalone/users_objects/DomainSetTooltip.vue
- src/components/standalone/users_objects/DomainSets.vue
- src/components/standalone/users_objects/HostSetTooltip.vue
- src/components/standalone/users_objects/HostSets.vue
- src/components/standalone/users_objects/ObjectTooltip.vue
- src/components/standalone/users_objects/ObjectUsages.vue
- src/composables/useMwan.ts
- src/composables/useObjects.ts
- src/composables/useRuleForm.ts
- src/stores/standalone/objects.ts
Adding support for objects in MWAN rules
Ref:
- Issue: https://github.com/NethServer/nethsecurity/issues/671
- Merge after: https://github.com/NethServer/nethsecurity/pull/674
---
Images:
> feat(mwan): added object support to mwan

- src/components/standalone/firewall/rules/SourceOrDestinationRuleColumn.vue
- src/stores/standalone/objects.ts
Ref: 
- merged with: https://github.com/NethServer/nethsecurity/pull/674
- issue: https://github.com/NethServer/nethsecurity/issues/697
> fix: reverting some changes made to backend

- src/components/standalone/openvpn_rw/RWAccountsTable.vue
Add pagination to OpenVPN Road Warrior accounts table
> fix: add pagination to openvpn rw accounts table

- public/i18n/en/translation.json
- src/components/standalone/report/ReportContent.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/721
> fix: disable "Open report" button in controlled unit

- package-lock.json
- package.json
- public/i18n/en/translation.json
- src/components/standalone/openvpn_rw/RWAccountsManager.vue
- src/components/standalone/users_objects/DomainSets.vue
- src/components/standalone/users_objects/HostSets.vue
- src/views/standalone/users_objects/ObjectsView.vue
- OpenVPN Road Warrior: use NeDropdownFilter component instead of NeCombobox in VPN accounts table
- Objects: add object type and IP version filters in host sets table
- Objects: add IP version filters in domain sets table
> refactor: use NeDropdownFilter

- src/components/standalone/dns_dhcp/LeasesTable.vue
DNS and DHCP: use a responsive and paginated table for static and dynamic leases tables
> refactor: import table from vue-components for leases

- public/i18n/en/translation.json
- src/components/standalone/firewall/nat/CreateOrEditNatRuleDrawer.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/720
> fix: nat rules, add 0.0.0.0/0 as destination address

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .prettierignore
- README.md
Just removing CHANGELOG.md from prettier and updating actions
Adding documentation on how to release
> ci: tooling maintanance

- env.d.ts
- package-lock.json
- package.json
- public/i18n/en/translation.json
- src/components/controller/units/UnitsTable.vue
- src/stores/controller/units.ts
- vite.config.ts
Implementing what said in [this issue](https://github.com/NethServer/nethsecurity/issues/721#issuecomment-2329479009).
> Controller version awareness

- src/components/standalone/dns_dhcp/LeasesTable.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/740
> fix: leases table pagination

- src/components/controller/units/UnitsTable.vue
Fixes issue raised by: https://github.com/NethServer/nethsecurity/issues/721#issuecomment-2340699430
> fix(controller): issue with opening unit with tooltip available

- src/components/standalone/openvpn_rw/CreateOrEditRWServerDrawer.vue
- src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/752
> fix(openvpn): fixed default mode in tunnel creation

- src/components/standalone/firewall/nat/NatHelpers.vue
- src/components/standalone/firewall/nat/NatHelpersTable.vue
- Highlight enabled modules
- Don't sort modules by status
Ref:
- https://github.com/NethServer/nethsecurity/issues/724
> fix: minor improvements to nat helpers ui

- src/components/standalone/dns_dhcp/DnsRecords.vue
- src/components/standalone/dns_dhcp/DynamicLeases.vue
- src/components/standalone/dns_dhcp/StaticLeases.vue
> fix(dhcp): make search case insensitive

- public/i18n/en/translation.json
- src/views/standalone/system/ControllerView.vue
Modal: 
https://github.com/user-attachments/assets/280ec031-cf49-4185-8751-917a9e9c3b3a
Ref:
- https://github.com/NethServer/nethsecurity/issues/754
> fix(controller): enhanced connection process

- public/i18n/en/translation.json
- src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
- src/components/standalone/firewall/nat/NatHelpersTable.vue
- src/components/standalone/qos/CreateOrEditQoSInterfaceDrawer.vue
- src/views/standalone/firewall/ZonesAndPolicies.vue
- Add **Logging** toggle in create/edit zone drawer
Other changes:
- Minor style fixes to zones table
- Minor fixes in NAT helper table and QoS drawer
Ref:
- https://github.com/NethServer/nethsecurity/issues/807
> feat(zones): add logging toggle

- src/components/standalone/certificates/CertificatesTable.vue
- src/components/standalone/firewall/nat/NatRulesTable.vue
Import NeTable from vue-components in:
- **System > Certificates** table
- **Firewall > NAT > NAT rules** table
> refactor: import new NeTable

- package-lock.json
- package.json
Bump @nethesis/vue-components@1.5.1, now using Vue 3.5
> chore: bump @nethesis/vue-components@1.5.1

- src/components/standalone/security/threat_shield/SettingsTab.vue
Change position of **Ban time** in **Threat shield** settings.
Ref:
- https://github.com/NethServer/nethsecurity/issues/881
> style: fix position of Ban time in Threat shield

- package-lock.json
- package.json
- vite.config.ts
I've been using it for a while, since it was only locally, I'm suggesting to use it for everyone, having the benefits of a browser-free vue debug tools directly in the webpage.
> build: adding vue devtools for dev environment

- src/composables/useRuleForm.ts
Fixing issue when editing default rule, the field was wrongly addressed as required even if when editing it's a mere placeholder.
Ref:
- Internal discussion: https://mattermost.nethesis.it/nethesis/pl/znaqcfmdujfh3kknuq755s5pse
> fix(mwan): fixing validation on default rule

- src/components/NeBreadcrumbs.vue
Adding NeBreadcrumb component
Closes: https://github.com/NethServer/nethsecurity/issues/934
> feat(components): added NeBreadCrumbs

- src/i18n/en/translation.json
- src/views/standalone/security/FlashStartView.vue
Implement subscription information retrieval with error handling in FlashStartView and add new translation keys for the disabled state and subscription info.
https://github.com/NethServer/nethsecurity/issues/926
https://github.com/user-attachments/assets/316af41d-dace-4b68-8d2e-dbf55b7404a1
> Add subscription info fetching and new translations for FlashStart state

- src/components/standalone/monitoring/VpnMonitor.vue
Fix **Monitoring > Real time monitor > VPN**: display an empty state if an OVPN server is present but not yet configured.
Ref:
- https://github.com/NethServer/nethsecurity/issues/943
> fix(monitoring): handle ovpn server not configured

- src/components/standalone/monitoring/TrafficMonitor.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/900
> fix(monitoring): shrank text and rearranged cards

- src/i18n/en/translation.json
- src/i18n/it/translation.json
Adding more context to the "cannot access due to missing update" modal.
> fix(controller): updated cannot connect message

- src/components/standalone/monitoring/TrafficMonitor.vue
Forgot a case for hosts with wider screens
Ref:
- https://github.com/NethServer/nethsecurity/issues/900
> fix(monitoring): missing css for hosts

- src/components/standalone/dashboard/SystemInfoCard.vue
- src/i18n/en/translation.json
- src/i18n/it/translation.json
- src/views/standalone/system/UpdateView.vue
Parsing the new error messages coming from the API
Ref:
- https://github.com/NethServer/nethsecurity/pull/990
> fix(updates): gracefully handle error for updates

- src/views/standalone/system/UpdateView.vue
Ref:
- https://github.com/NethServer/nethsecurity/pull/1000
> fix(updates): typos in tranlsation strings

- src/views/standalone/system/UpdateView.vue
Ref:
- https://github.com/NethServer/nethsecurity/pull/1000
---
> fix(updates): correctly enable updates page even with errors

- src/components/standalone/firewall/rules/FirewallRulesTable.vue
Improve also rule line readability
NethServer/nethsecurity#899
> fix(rules): correctly set action color

- src/components/standalone/monitoring/NetifyInformaticsContent.vue
- src/i18n/en/translation.json
Improve user experience by updating notification titles related to metadata sending and enhancing translation keys for better clarity.
https://github.com/NethServer/nethsecurity/issues/981
https://github.com/user-attachments/assets/9011d249-386b-4b67-9610-d3d60a65e3bb
> fix(netify): update notification titles and improve metadata sending descriptions

- src/components/standalone/security/ips/IpsDisableRuleDrawer.vue
- src/components/standalone/security/ips/IpsDisabledRules.vue
- src/components/standalone/security/ips/IpsEnableRuleModal.vue
- src/components/standalone/security/ips/IpsFilterBypass.vue
- src/i18n/en/translation.json
- src/views/standalone/security/IpsView.vue
Added:
- Removal of disabled rules
- Added rule removal
- Listing of disabled rules
Ref: https://github.com/NethServer/nethsecurity/issues/1017
> feat(ips): rule management

- src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue
- src/i18n/en/translation.json
Ref:
- https://github.com/NethServer/nethsecurity/issues/989
> fix(firewall): allow rules with same src/dest zone

- src/components/standalone/dashboard/IpsServiceCard.vue
- src/components/standalone/security/ips/IpsDisabledRules.vue
- src/components/standalone/security/ips/IpsEventList.vue
- src/components/standalone/security/ips/IpsFilterBypass.vue
- src/components/standalone/security/ips/IpsSuppressedAlerts.vue
- src/i18n/en/translation.json
- src/stores/standalone/ipsStatus.ts
- src/views/standalone/security/IpsView.vue
Fixed some styling due to changes requested in
- https://github.com/NethServer/nethsecurity/issues/976
> fix(ips): fixed styling

- src/components/standalone/account/ChangePassword.vue
- src/i18n/en/translation.json
Implements
- https://github.com/NethServer/nethsecurity/pull/1077
> fix(account): added old password input

- package.json
- src/components/standalone/ssh/SshKeys.vue
- src/i18n/en/translation.json
Refactored page to use API coming from https://github.com/NethServer/nethsecurity/pull/1078
> refactor(ssh): removing old api calls 

- src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
Ref:
- https://github.com/NethServer/nethsecurity/issues/1117
> fix(tunnel): fixed missing validation messages

- src/components/standalone/monitoring/ConnectivityMonitor.vue
Due to changes coming from https://github.com/NethServer/nethsecurity/pull/1174, API calls are adjusted.
Ref: https://github.com/NethServer/nethsecurity/issues/1175
> fix(monitoring): adjusting public IP resolution

- src/components/standalone/dns_dhcp/EditDhcpInterfaceDrawer.vue
- src/i18n/en/translation.json
NethServer/nethsecurity#1070
Before:
After:
> fix(dhcp): improve visualization of custom options

- src/components/standalone/account/two_fa/ConfigureTwoFaDrawer.vue
- src/components/standalone/ssh/SshKeys.vue
- src/stores/standalone/sudo.ts
Review of: https://github.com/NethServer/nethsecurity/issues/1164
> fix(sudo): fixed some corner cases

- src/components/standalone/account/two_fa/RevokeTwoFa.vue
Ref: https://github.com/NethServer/nethsecurity/issues/1164
> fix(two fa): remove error in case of unauthorized action

- src/components/AxiosErrorModal.vue
- src/i18n/en/translation.json
- src/i18n/it/translation.json
Add message inside `AxiosErrorModal`: "Make sure the unit is updated to the most recent version."
> fix: improve message in axios error modal

- src/components/standalone/certificates/CertificatesTable.vue
- src/views/standalone/system/CertificatesView.vue
Closes: https://github.com/NethServer/nethsecurity/issues/1226
> fix(certificates): enable deletion of pending certificates

- src/components/standalone/subscription/UnitSubscription.vue
- src/i18n/en/translation.json
- src/views/standalone/system/SubscriptionView.vue
Closes https://github.com/NethServer/nethsecurity/issues/1176
> feat(subscription): added sync status

- src/components/standalone/NeMultiTextInput.vue
- src/components/standalone/security/FlashstartContent.vue
- src/i18n/en/translation.json
Added Proplus option selection
Fixed a bug on NeMultiTextInput that forbids deletion of just the first item
Closes https://github.com/NethServer/nethsecurity/issues/1162
Screenshot:
> feat(flashstart): proplus UI

- src/components/standalone/StandaloneTopBar.vue
- src/i18n/en/translation.json
Lucia pointed out that this was missing, was there a reason why?
> feat: added subscription icon on top

- package.json
- src/components/standalone/security/threat_shield/SearchBannedIp.vue
- src/i18n/en/translation.json
Added tooltip as requested by: https://github.com/NethServer/nethsecurity/issues/924#issuecomment-2904215932
Also bumped api version planning for release.
> fix(banip): added tooltip into search

- src/i18n/it/translation.json
Fix `page` parameter of `go_to_page` i18n string in Italian translation.
> fix: parameter of go_to_page i18n string

- src/components/controller/units/OpenSshModal.vue
Controller: fix SSH keys listing while opening the SSH terminal of a unit
> fix: ssh keys list while opening unit ssh terminal

- src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
- src/i18n/en/translation.json
Closes: https://github.com/NethServer/nethsecurity/issues/1220
Needs: https://github.com/NethServer/nethsecurity/pull/1246
> fix(port forward): enabled possibility to set rules for firewall

- src/components/controller/units/OpenSshModal.vue
Controller: fix passphrase (public key) check while opening the SSH terminal of a unit
See also:
- https://github.com/NethServer/nethsecurity-ui/pull/572
> fix: passphrase (public key) access to unit ssh

- src/stores/controller/controllerLogin.ts
Controller: fix "Remember me" checkbox on login page
> fix(controller): remember me checkbox on login

- src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
Closes: https://github.com/NethServer/nethsecurity/issues/1219
> fix(zones): allow names not starting with number

- src/i18n/en/translation.json
- src/views/standalone/network/ReverseProxyView.vue
- src/views/standalone/wizard/SshStep.vue
- src/views/standalone/wizard/SummaryStep.vue
- **fix: added additional removal of password auth**
- **fix: extended time of animation, tries to redirect to correct url**
- **feat: added banner if input wan rule is disabled**
> fix(wizard): few improvements to UX

- src/components/standalone/firewall/PortForwardTable.vue
- src/i18n/en/translation.json
- src/i18n/it/translation.json
- src/views/standalone/firewall/PortForward.vue
Closes: https://github.com/NethServer/nethsecurity/issues/1286
> fix(port forward): added automated tag if entry is managed by system

- src/i18n/en/translation.json
- src/views/standalone/system/ControllerView.vue
Closes NethServer/nethsecurity#1035
> feat(standalone): controller, add unit description

- src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
Closes: https://github.com/NethServer/nethsecurity/issues/1291
Needs: https://github.com/NethServer/nethsecurity/pull/1326
> fix(firewall): generating `ns_link` accordingly to response

- src/components/standalone/backup_and_restore/BackupContent.vue
As per Lucia request
This is part of https://github.com/NethServer/nethsecurity/issues/1297
> fix(backup): remove primary configure passphrase button

- src/i18n/en.json
- src/i18n/it.json
- src/views/standalone/system/ControllerView.vue
https://github.com/user-attachments/assets/fc76f51d-b6de-45c9-b8db-673c3c90a1c5
Needs: https://github.com/NethServer/nethsecurity/pull/1374
> fix(ns-plug): allow edit of description for controller

- src/components/standalone/dashboard/HaStatusCard.vue
- src/i18n/en.json
Do not show info inside the tooltip for the backup node.
Fixes: NethServer/nethsecurity#1380
Merge after NethServer/nethsecurity#1369
> fix(standalone): dashboard, improve HA widget

- src/components/standalone/firewall/rules/FirewallRulesTable.vue
- src/components/standalone/wireguard/PeerTableRow.vue
- src/components/standalone/wireguard/WireguardPeerTunnelList.vue
- src/components/standalone/wireguard/WireguardServerTunnelList.vue
also fixed positioning of automated badge in firewall rules
Closes https://github.com/NethServer/nethsecurity/issues/1352
> feat: added live update for wireguard views

- src/components/standalone/wireguard/TunnelDrawer.vue
- src/i18n/en.json
Small fixes of validation errors
> fix(wireguard): ui error fixes
