public/i18n/en/translation.json
src/assets/main.css
src/components/standalone/InputLayout.vue
src/components/standalone/ssh/SshConfig.vue
src/components/standalone/ssh/SshKeys.vue
src/lib/validation.ts
src/views/standalone/system/SSHView.vue

Added SSH page, with config edit and key upload

Added SSH Configuration

---

src/lib/standalone/ubus.ts

Detect validation errors while invoking `/ubus/call` and throw a `NeValidationError` to properly handle the error validations on the UI.
See: https://github.com/NethServer/nethsecurity/pull/163

Handle validation errors on ubusCall

---

public/i18n/en/translation.json
src/router/index.ts
src/views/standalone/LogsView.vue

~~Currently evaluating what can be done to highlight the searched text in the UI, the solution found is highly inefficient and hence not included in PR, [just commented out in the code](https://github.com/NethServer/nethsecurity-ui/pull/61/files#diff-a97c9a3ab6a48c6bca4def6c506ac9489cf97a8f9c7f1c56e97d1ac1a48ba190R100).~~
I appears that if an empty regex is given, it loads too much the task. Why? No clue.
Added cards for TODOs: 
- https://trello.com/c/czrHLZqn/147-uilogs-add-loading-placeholders
- https://trello.com/c/xJl5sGQR/148-uilogs-add-less-expensive-search-highlight

feat: added logs view

---

package.json

Due to unknown issues, `husky` hook was missing from `package.json`

build: added husky missing hooks

---

public/i18n/en/translation.json
public/i18n/it/translation.json
src/components/standalone/FilterableListItemLayout.vue
src/components/standalone/NeMultiTextInput.vue
src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
src/views/standalone/firewall/PortForward.vue

- update translation in NeEmptyState when no port forward is found
- show separate label on toggles in the add/edit port forward drawer
- hide add button from description when no items are present in PortForward view and FilterableListItemLayout
- enable port forward toggle by default when adding
- hide advanced settings when drawer is closed
- fix optional label size in NeMultiTextInput
- show a text input for the restrict ip NeMultiTextInput by default
- remove the restrict ip required validator: empty items are filtered out on add/edit request, ip validation is performed only on filled textinputs

Port forward: fix minor ui issues

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
src/components/standalone/openvpn_tunnel/TunnelTable.vue

- Fix error in drawer if `local` or `remote` is not included in payload
- Show empty local networks property in table

OpenVPN tunnel: fix minor ui issues

---

public/i18n/en/translation.json
src/components/standalone/system_settings/GeneralSettings.vue

The button didn't work as expected: the
change to system configuration seems ignored
by ubus
Card: https://trello.com/c/BFutxOq0/198-ntp-time-is-wrong

fix(settings): remove sync with browser button

---

src/components/standalone/update/UploadImageDrawer.vue

- Fix issue where state would not be cleared properly when closing the upload image drawer (after uploading a file)

Update: clear state when closing upload image drawer

---

public/i18n/en/translation.json
src/components/standalone/dns_dhcp/EditDhcpInterfaceDrawer.vue

If the range is invalid, the server now raises a specific error. Before this change, the server validation was not visible.
Card: https://trello.com/c/dTaFNmqv/219-qa-dns-dhcp-various

fix: dhcp, show server validation error

---

src/components/standalone/ssh/SshKeys.vue

If the authorized_keys file was empty, the UI was
displaying the error toast notification
Card: https://trello.com/c/ZymrMQnR/226-ssh-add-api-for-authorized-keys
See also: https://github.com/NethServer/nethsecurity/pull/241

fix: ssh, prevent default axios error

---

public/i18n/en/translation.json
src/components/standalone/firewall/DeletePortForwardModal.vue
src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
src/views/standalone/network/InterfacesAndDevicesView.vue

Read the list of zones that can be selected for device configuration from the backend, using `ns.devices list-zones-for-device-config` API.
See also: https://github.com/NethServer/nethsecurity/pull/254

feat(devices): read allowed zone from backend

---

src/components/standalone/openvpn_tunnel/TunnelManager.vue
src/components/standalone/openvpn_tunnel/TunnelTable.vue

Card: https://trello.com/c/6wuSVOgb/211-openvpn-tunnel-missing-connected-disconnected-info
Tunnel enabled but not connected:
Tunnel disabled and not connected:
Tunnel enabled and connected:
~~Requires: https://github.com/NethServer/nethsecurity/pull/247~~ Patch is already in main branch

feat: vpn tunnel, show connected flag

---

src/components/standalone/openvpn_rw/CreateOrEditRWServerDrawer.vue
src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue

Valid values are:
- empty
- lzo (not lz0)
- lz4

fix(openvpn): change compression param value

---

src/components/standalone/openvpn_tunnel/DeleteTunnelModal.vue
src/components/standalone/openvpn_tunnel/DownloadTunnelModal.vue
src/components/standalone/openvpn_tunnel/ImportConfigurationDrawer.vue

- Fix issue where the error notification would display even if no error is encountered in the download tunnel modal, delete tunnel modal and import configuration drawer
Cards:
- https://trello.com/c/aDkk2gr3/261-openvpn-tunnel-error-when-importing-client-config
- https://trello.com/c/0qn3rwEO/260-openvpn-tunnel-error-when-downloading-client-config

OpenVPN tunnel: fix notification showing even if no error is encountered

---

src/components/standalone/openvpn_rw/CreateOrEditRWServerDrawer.vue

- Fix issue where the bridge options would not be fetched in the create/edit RW instance drawer
Card: https://trello.com/c/ViRQATGa/264-openvpn-rw-unable-to-select-br-lan-bridge-in-openvpn-road-warrior-configuration

OpenVPN RW: fetch bridge when creating or editing a RW instance

---

public/i18n/en/translation.json

The OpenVPN server instance is automatically committed.
Card: https://trello.com/c/GQjEHIVQ/258-openvpn-rw-reverting-after-deleting-rw-server-breaks-openvpn-rw-page

fix: i18n, improve delete modal

---

src/components/standalone/qos/CreateOrEditQoSInterfaceDrawer.vue
src/views/standalone/network/QoSView.vue

- Exclude already configured interfaces from list in create/edit drawer
Card: https://trello.com/c/OnJqKKbI/269-qos-drawer-shows-already-configured-interfaces

QoS: exclude already configured interfaces from create/edit drawer

---

public/i18n/en/translation.json
src/components/standalone/interfaces_and_devices/CreateVlanDeviceDrawer.vue

- Move VLAN device type under advanced settings in the create VLAN device drawer
Card: https://trello.com/c/nNY0G6HV/221-devices-and-interfaces-improvement-on-vlan

Devices and interfaces: move VLAN device type under advanced settings

---

public/i18n/en/translation.json
src/components/standalone/NeMultiTextInput.vue
src/components/standalone/interfaces_and_devices/CreateOrEditAliasInterfaceDrawer.vue

- Use NeMultiTextInput on the create/edit alias interface drawer to maintain uniformity
- Simplify validation with the new inputs in mind
- Add option, in NeMultiTextInput, to focus on the first text-input if available
Card: https://trello.com/c/9OWsVjah/222-devices-and-interfaces-alias-improvement-ui

Devices and interfaces: rework alias interface drawer to use NeMultiTextInput

---

src/StandaloneApp.vue
src/components/standalone/update/UpdatePackagesModal.vue
src/views/standalone/system/UpdateView.vue

- Avoid showing toast notification when the system is rebooting because of a system update
- Fix incorrect package payload field (`latestVersion` instead of `lastVersion`)
- Add maximum height and overflow scroll on package updates drawer, to avoid cases where it is expanded too much when there are many packages to upload
- Fix buttons in package updates drawer not being disabled properly when making an update request
Card: https://trello.com/c/2gT1g47F/227-update-page-notification-error-while-updating-rebooting

Update page: avoid showing error notification on system reboot, minor UI fixes

---

src/components/standalone/reverse_proxy/CreateOrEditProxyDrawer.vue

- Avoid showing pending certificates in create/edit proxy drawer 
Card: https://trello.com/c/Eo4w1OXj/291-reverseproxy-ui-shows-unobtained-certificates-when-creating-or-editing-domains

Reverse proxy: avoid showing unobtained certificates when creating or editing domains

---

src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue

Show **Ports** field inside rule drawer only if the **Protocols** selected contain at least "TCP" or "UDP".
Card: https://trello.com/c/hJ3kSJAb/286-firewall-rules-port-in-rules-only-for-tcp-and-udp

fix(fw rules): show ports only on tcp/udp rules

---

src/lib/validation.ts

- Use new URL validator for destination URL, allowing for the usage of domains such as `http(s)://localhost`. The new validator makes use of Javascript's `URL` object instead of relying on a regex, allowing for more flexibility in the URL definition.
Card: https://trello.com/c/mCck9st8/293-reverse-proxy-ui-doesnt-accept-localhost-as-destination-url

Reverse proxy: use new URL validation for destination url

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue

- Use host validation for remote hosts, allowing for IP or hostnames (instead of allowing only IPs)
Card: https://trello.com/c/6jA5ZsZd/295-openvpn-tunnels-cant-use-an-hostname-inside-the-remote-hosts-field

OpenVPN Tunnel: use host validation for remote hosts instead of ip

---

src/components/standalone/certificates/CreateLetsEncryptCertificateDrawer.vue
src/components/standalone/reverse_proxy/CreateOrEditProxyDrawer.vue
src/lib/validation.ts

- Allow usage of wildcard domains when requesting a Let's Encrypt certificate, done by adding an additional argument in the FQDN validator, which can be used to allow or disallow the usage of wildcards
Card: https://trello.com/c/Yl5g0dEC/297-certificates-validation-error-for-wildcard-domains

Certificates: allow wildcard domains when requesting a Let's Encrypt certificate

---

src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue

Show "Enable IPv6" checkbox for PPPoE interfaces
Other changes:
- Fix username/password management for PPPoE interfaces
Card: https://trello.com/c/PYrd3n37/301-interfaces-pppoe-ipv6
See also:
- https://github.com/NethServer/nethsecurity/pull/304

fix: ipv6 flag management for pppoe ifaces

---

public/i18n/en/translation.json
src/lib/standalone/network.ts
src/views/standalone/network/InterfacesAndDevicesView.vue

Fix display and management of interfaces configured on deleted zones:
- Interface can be reconfigured or removed
- Aliases (if any) cannot be edited or deleted
Card:
- https://trello.com/c/SAG4TmDP/304-interface-with-deleted-zone-is-blocked
See:
- https://github.com/NethServer/nethsecurity/pull/316

fix: ifaces configured on deleted zones

---

src/components/standalone/qos/CreateOrEditQoSInterfaceDrawer.vue

This PR fixes the selected interface not showing when editing QoS interface. It was caused by the additional filter introduced with one of the latest PRs to avoid displaying already selected interfaces. Now this filter is only applied when creating a QoS interface rather than editing it.
Card: https://trello.com/c/crPiIiGg/323-qos-bad-interface-selected

QoS: fix selected interface not showing when editing QoS interface

---

src/components/standalone/dns_dhcp/EditDhcpInterfaceDrawer.vue

- Include option number in DHCP options when editing DHCP interface
Card: https://trello.com/c/2ei2yD64/326-dhcp-allow-option-number-in-advanced-section

DHCP: include option number in DHCP options when editing interface

---

public/i18n/en/translation.json
src/components/standalone/account/two_fa/RevokeTwoFaModal.vue
src/components/standalone/dpi/DeleteDpiRuleModal.vue
src/components/standalone/firewall/rules/DeleteFirewallRuleModal.vue
src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue
src/components/standalone/interfaces_and_devices/DeleteAliasModal.vue
src/components/standalone/interfaces_and_devices/DeleteBondModal.vue
src/components/standalone/interfaces_and_devices/DeleteDeviceModal.vue
src/components/standalone/interfaces_and_devices/DeviceButtons.vue
src/components/standalone/interfaces_and_devices/UnconfigureDeviceModal.vue
src/lib/standalone/network.ts
src/views/standalone/network/InterfacesAndDevicesView.vue

UI is quite intricate, but here's what I've tried to accomplish so far:
- deleting the `zone` param when creating a bond, allows to configure the bond according to user preference, also removed the radio selection entirely for bonds
- bond naming is **weird** (and it's a compliment). When you define a named bond, the software first creates a `bonding-<name>` device for said bond, then when device gets up it's renamed to `bond-<name>`. IF THE `bond-<name>` EXCEEDS THE 15 CHARACTERS IT WILL BE STUCK IN THE FIRST STATE. Hence there's a custom check for bond name length.
- Added delete bond modal using custom call from API
- Due to changes in the API responses, there's an additional `bond_interface` field in the DeviceOrIface interface.
- Added additional check in `isBond` function, checking …

refactor: bond management processes

---

src/components/standalone/firewall/rules/SourceOrDestinationRuleColumn.vue

- Allow showing more than one address on source and destination address fields, showing at most two values
Here's an image showing how the table looks after these changes:
Card: https://trello.com/c/NjNgR4na/329-firewall-rules-multiple-address-page-organization

Firewall rules: allow showing more than one address on source and destination address fields

---

src/views/standalone/network/InterfacesAndDevicesView.vue

- Display packets in a more readable format in the Devices and interfaces page: 
- Value is formatted depending on the browser's locale
- Use M unit if packets are above 1 million
Card: https://trello.com/c/dNrGfN8n/324-interfaces-humanify-packet-count

Interfaces: display packets in a more readable format

---

public/i18n/en/translation.json
public/i18n/it/translation.json
src/components/standalone/firewall/CreateOrEditZoneDrawer.vue
src/components/standalone/firewall/nat/CreateOrEditNatRuleDrawer.vue
src/components/standalone/firewall/nat/NatRulesTable.vue
src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue
src/components/standalone/firewall/rules/FirewallRulesTable.vue
src/views/standalone/firewall/ZonesAndPolicies.vue

Don't translate firewall/NAT targets (DROP, REJECT, ACCEPT, SNAT, MASQUERADE) and show them in uppercase on the UI

fix: show firewall/nat targets in uppercase

---

src/components/standalone/ipsec_tunnel/CreateOrEditTunnelDrawer.vue

Remote IP address field of IPsec tunnel now accept:
- an IP addresses
- a hostname
- "any"

fix: validation of IPsec remote IP address

---

src/components/standalone/reverse_proxy/CreateOrEditProxyDrawer.vue

- Disable type and domain fields on edit
Card: https://trello.com/c/g1s50b0E/357-proxy-pass-unable-to-modify-existing-domain

Reverse proxy: disable type and domain fields when editing entry

---

src/components/standalone/firewall/rules/SourceOrDestinationRuleColumn.vue

- Fix issue where the source in the output rules or the destination in the input rules would not have the correct opacity if disabled
Card: https://trello.com/c/sL9NvFmw/355-firewall-disabled-rule-label-color

Firewall: use correct opacity in disabled source and destination fields in input and output rules

---

src/components/standalone/multi-wan/PolicyCreator.vue
src/components/standalone/multi-wan/PolicyEditor.vue
src/stores/standalone/firewall.ts
src/views/standalone/firewall/ZonesAndPolicies.vue

Implementing changes coming from NethServer/nethsecurity#360
Card: https://trello.com/c/LFCTBvU7/351-aliases-among-interfaces

 fix: retrieving zones without aliases in mwan and firewall

---

src/composables/usePolicyForm.ts

Swap behaviour has been criticized due to "not deleting" the empty fields when moving to the "Custom" option, this will address the issue.
Updated behaviour:
[Screencast from 2024-03-08 15-27-04.webm](https://github.com/NethServer/nethsecurity-ui/assets/8052641/516fb4ab-4250-4524-913d-332d34844b0c)

feat: cleaning up gateways on policy

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue

- Use `AES-256-CBC` as the default cipher when creating a P2P tunnel. When switching the topology to subnet, the default value will remain the previous one (`AES-256-GCM`).

OpenVPN tunnel: use different default cipher when creating a P2P tunnel

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue

- Fix an issue where the user couldn't edit a previously added P2P tunnel. This was caused by the presence of a validation on the `vpnNetwork` field which was not present if the tunnel was a P2P one.
Card: https://trello.com/c/V2Q4MhYl/378-cant-edit-openvpn-p2p-tunnel-server

OpenVPN tunnel: fix validation error when editing p2p tunnel

---

public/i18n/en/translation.json
src/components/standalone/backup_and_restore/MigrationDrawer.vue
src/components/standalone/backup_and_restore/ModalDownloadBackup.vue
src/components/standalone/backup_and_restore/RestoreContent.vue
src/components/standalone/backup_and_restore/SetPassphraseDrawer.vue
src/lib/standalone/fileUpload.ts

- Refactor `fileUpload` lib to use the new `/api/files` end and add functions to download and delete file based on filename
- Use new api flow for backup, restore and migration to handle file uploads, allowing for larger file sizes on upload
Card: https://trello.com/c/k0b38yGx/380-ubus-fails-to-handle-files-larger-than-70k

Backup, restore and migration: use new api flow to handle file uploads

---

src/lib/standalone/network.ts

Before this commit, a vlan over a bond was rendered as a bond.
Card: https://github.com/NethServer/nethsecurity-ui/pull/217

fix: network lib, fix vlan over bond visualization

---

src/composables/useTabs.ts

This PR fixes an issue occuring with the `useTabs` composable where, when switching page, the `watch` callback would be called on both the source page and the target one, causing a wrong tab value being set. To fix the issue, a check has been added to ensure the tab does not update if the current path is different compared to the page's route path.

Fix: avoid changing tabs when switching page

---

src/components/standalone/security/threat_shield/BlocklistTable.vue
src/composables/useItemPagination.ts

This PR refactors the `useItemPagination` composable to better handle reactivity, allowing its outputs to be refreshed when the input changes. To allow for reactivity, a ref or function getter has to be passed to the composable. An example could be the following:
```
const { currentPage, pageCount, paginatedItems } = useItemPagination(() => props.blocklists, {
itemsPerPage: 10
})
```

Refactor useItemPagination composable to better handle reactivity

---

package-lock.json
package.json
public/i18n/en/translation.json
src/components/ToastNotificationsArea.vue
src/components/controller/units/UnitsTable.vue
src/components/standalone/StandaloneTopBar.vue
src/components/standalone/account/two_fa/TwoFactorAuth.vue
src/components/standalone/dashboard/SystemInfoCard.vue
src/components/standalone/dns_dhcp/DeleteStaticLeaseModal.vue
src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
src/components/standalone/system_settings/GeneralSettings.vue
src/components/standalone/users_database/CreateOrEditDatabaseDrawer.vue
src/views/controller/AccountView.vue
src/views/controller/UnitTerminalView.vue
src/views/standalone/system/ControllerView.vue

Import NeTextArea from vue-components
Other changes:
- Show toast notifications on top of drawers and modals
- Show a warning if using default hostname 'NethSec'
- Minor style fixes

chore: import NeTextArea from vue-components

---

package-lock.json
package.json
src/stores/standalone/uciPendingChanges.ts

Some browsers (e.g. Firefox) detect an axios error if the page is reloaded just after a POST request.
This happens e.g. when committing UCI changes: the UI waits for the API call to complete and reload the page immediately after.
To mitigate this issue this PR just adds a `setTimeout` before the page reload.
Other changes:
- Bump axios version

Fix axios error when committing changes

---

src/components/standalone/firewall/CreateOrEditZoneDrawer.vue

Fix radio buttons IDs in **Zones & Policies** page. Radio IDs are now unique, before this change a glitch happened when selecting **Traffic to same zone** radio by clicking on the label of one of its options.

fix: radio buttons IDs in Zones page

---

src/views/standalone/vpn/IPsecTunnelView.vue

Previously, the skeleton was visible until the first execution of the interval
Related to https://github.com/NethServer/nethsecurity-ui/pull/251

fix: ipsec tunnel, hide skeleton after first load

---

public/i18n/en/translation.json
src/components/standalone/dns_dhcp/CreateOrEditDnsRecordDrawer.vue
src/components/standalone/dns_dhcp/CreateOrEditStaticLeaseDrawer.vue
src/components/standalone/dns_dhcp/DhcpManager.vue
src/components/standalone/dns_dhcp/ScanInterfaceCard.vue
src/components/standalone/dns_dhcp/ScanNetwork.vue
src/components/standalone/dns_dhcp/ScanResultsTable.vue
src/views/standalone/network/DnsDhcpView.vue

Add **Scan network** tab in **DHCP & DNS** page. It is used to discover devices and assign them IP reservations or DNS records.
See:
- https://github.com/NethServer/nethsecurity/issues/460

DHCP & DNS: scan network

---

.vscode/extensions.json
public/i18n/en/translation.json
src/ControllerApp.vue
src/StandaloneApp.vue
src/components/AxiosErrorModal.vue
src/components/standalone/certificates/CreateLetsEncryptCertificateDrawer.vue
src/components/standalone/dashboard/InternetConnectionCard.vue
src/components/standalone/dashboard/SystemInfoCard.vue
src/components/standalone/security/FlashstartContent.vue
src/views/standalone/StandaloneDashboardView.vue

Dashboard page: show a warning on **Internet connection** card if there are one or more WANs with a static IP address and no DNS forwarder has been configured.
Other changes:
- Fix logout on 401 error
- Fix warning for `<i18n-t>` elements
- Remove suggestion for deprecated vscode extension

Show a warning on the dashboard if DNS is not configured

---

package-lock.json
package.json
public/i18n/en/translation.json
src/components/controller/units/SendOrRevokeSshKeyDrawer.vue
src/components/standalone/backup_and_restore/RestoreContent.vue

Simplify validation of selected restore file by:
- Removing manual file name syntax validation
- Restricting the type of files that can be selected for the restore
See:
- https://github.com/nethesis/vue-components/pull/58

Fix validation of selected restore file

---

public/i18n/en/translation.json
src/components/standalone/backup_and_restore/RestoreContent.vue

Always show passhprase field while restoring: the user might upload a file encrypted or not, it's not known a priori.

fix: always show passhprase field while restoring

---

src/components/standalone/backup_and_restore/RestoreContent.vue

Always show passhprase field while restoring: the user might upload a file encrypted or not, it's not known a priori.

fix: always show passhprase field while restoring (2)

---

src/components/standalone/multi-wan/MultiWanGeneralSettings.vue
src/components/standalone/multi-wan/PolicyCreator.vue
src/components/standalone/multi-wan/PolicyEditor.vue
src/components/standalone/multi-wan/RuleCreator.vue
src/components/standalone/multi-wan/RuleEditor.vue

This pull request refactors multiple components to trim whitespace in input fields.
The affected components are RuleEditor.vue, RuleCreator.vue, PolicyEditor.vue, PolicyCreator.vue, and MultiWanGeneralSettings.vue.
The whitespace trimming is done using the v-model.trim directive.
This improves the user experience by automatically removing leading and trailing whitespace from input values.
https://github.com/NethServer/nethsecurity/issues/580

Refactor: Trim whitespace in input fields

---

public/i18n/en/translation.json
src/components/standalone/multi-wan/RuleCreator.vue
src/components/standalone/multi-wan/RuleEditor.vue
src/lib/validation.ts

This PR attemps to 
- fix a bug in validation of port range with `-`
- add tooltips to port of rule creator and editor
https://github.com/NethServer/nethsecurity/issues/580

add tooltip for ports in RuleEditor.vue

---

public/i18n/en/translation.json
src/components/standalone/multi-wan/RuleCreator.vue
src/components/standalone/multi-wan/RuleEditor.vue
src/composables/useMwan.ts
src/composables/useRuleForm.ts

This pull request refactors the multi-wan policy creator and editor to add a sticky connection feature. 
It also includes form validation for the sticky connection feature. 
The changes include modifications to the RuleCreator.vue and RuleEditor.vue components, as well as updates to the useMwan.ts and useRuleForm.ts files.
Prerequisites: 
- ns-api tag after https://github.com/NethServer/nethsecurity/pull/582
https://github.com/NethServer/nethsecurity/issues/581

Add sticky toggle to multi-WAN rule creation and editing

---

public/i18n/en/translation.json
src/components/standalone/backup_and_restore/RestoreContent.vue

This pull request includes a refactoring of the backup restoration process to handle validation errors more effectively. Additionally, new translations have been added to improve error messaging during backup restoration.
A function to clean the form when cancel or close has been added
REFs:
- https://github.com/NethServer/nethsecurity/pull/586
- https://github.com/NethServer/nethsecurity/issues/587

Refactor backup restoration validation handling and add new translations

---

public/i18n/en/translation.json

Add remote user database: fix i18n message format of **Custom user bind DN** field tooltip. The `@` character is special and requires this format: `{'@'}`

fix: i18n format of user bind dn tooltip message

---

public/i18n/en/translation.json
src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue

Firewall rules: show "Domain set cannot be used as both source and destination" if user selects the same domain set as source and destination of the rule.

fix: handle domain_set_conflict in fw rules

---

public/i18n/en/translation.json
public/i18n/it/translation.json

Blocklists are now available both for Enterprise and Community subscriptions

fix(i18n): change label for blocklist subscription

---

src/components/standalone/openvpn_rw/CreateOrEditRWServerDrawer.vue

The value of a `NeMultiTextInput` prop in the drawer "Create OpenVPN Road Warrior server" was previously changed by mistake.
In this  PR we revert it to its correct value.

fix: revert unwanted change in ovpn dhcp custom options

---

public/i18n/en/translation.json
src/components/standalone/multi-wan/RuleCreator.vue
src/components/standalone/multi-wan/RuleEditor.vue
src/composables/useRuleForm.ts

Changes:
- clean form after save
- mimic firewall rules form for a better user experience
Issue: NethServer/nethsecurity#671

Improve mwan rule form

---

src/components/standalone/openvpn_rw/CreateOrEditRWServerDrawer.vue

Fix OpenVPN RW IP pool management. Before this fix the UI raised an error if `ns.ovpnrw get-configuration` API returned an empty array as `ifconfig_pool` .

fix: openvpn rw ip pool

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue

Ref:
- https://github.com/NethServer/nethsecurity/issues/743

fix(openvpn): solved wrong mode when editing client tunnel

---

public/i18n/en/translation.json
src/components/standalone/firewall/nat/EditNatHelperDrawer.vue
src/components/standalone/firewall/nat/NatHelpers.vue
src/components/standalone/firewall/nat/NatHelpersTable.vue
src/components/standalone/firewall/nat/NatRulesContent.vue
src/stores/standalone/firewall.ts
src/views/standalone/firewall/NatView.vue

Ref:
- https://github.com/NethServer/nethsecurity/issues/724

feat: nat helpers UI

---

src/components/controller/units/UnitsTable.vue

It appears that semvers with correct format suffixes like `-1` does not
appears to be compatible with `satisfies` method. With everything else
it appears to be just fine.

fix(controller): parsing semver when connecting to unit

---

public/i18n/en/translation.json
src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue

Ref:
- https://github.com/NethServer/nethsecurity/issues/804

fix: ensure pppoe iface name has a max of 5 chars

---

package-lock.json
package.json
src/components/controller/ControllerTopBar.vue
src/components/standalone/StandaloneTopBar.vue

Use the new `menuClasses` prop of `NeDropdown` component to show Account menu on top of toast notifications
See:
- https://github.com/NethServer/nethsecurity/issues/821
- https://github.com/nethesis/vue-components/pull/72

fix: show Account menu on top of toast notifications

---

public/i18n/en/translation.json
src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue
src/components/standalone/users_objects/ObjectTooltip.vue
src/stores/standalone/objects.ts
src/views/standalone/firewall/PortForward.vue

feat(port forward): support multiple object types

---

public/i18n/en/translation.json
src/components/controller/units/ScheduleUpdateDrawer.vue
src/components/controller/units/UnitsTable.vue
src/components/controller/units/UpdateUnitsPackagesModal.vue
src/stores/controller/units.ts

fix(controller): show banner if updates are applied
fix(controller): disable update packages once launched

fix(controller): remote update adjustments

---

public/i18n/en/translation.json
src/components/standalone/openvpn_rw/RWAccountsManager.vue

This pull request adds a new feature to the OpenVPN module. It introduces the ability to download all user configurations at once. The "Download all user configurations" option is now available in the OpenVPN accounts table. This feature improves user experience and simplifies the process of managing user configurations.
https://github.com/orgs/NethServer/projects/10/views/2?pane=issue&itemId=80692610

Add option to download all user configurations in OpenVPN

---

src/components/standalone/security/threat_shield/SettingsTab.vue

Fixing wrong label assignment in syn_dos logging

fix(threatshield): fixing wrong label in toggle

---

src/components/standalone/multi-wan/RuleCreator.vue
src/composables/useRuleForm.ts

This pull request adds a length validation for the name rule in the `useRuleForm.ts` file. The validation ensures that the name is not more than 12 characters long. This validation is implemented in the `validateLengthNotMore12` function in the `validation.ts` file.
https://github.com/NethServer/nethsecurity/issues/835

fix(mwan): add length validation for name

---

public/i18n/en/translation.json
src/components/NotificationDrawer.vue
src/components/standalone/dashboard/SystemInfoCard.vue
src/views/standalone/system/UpdateView.vue

Improve the visibility of new release updates by replacing the current subtle blue "Update" link with a more prominent yellow triangle icon.
Other changes:
- Minor fixes in **Updates** page
- Fix style of icon in empty state of notification drawer

fix: improve new release available warning

---

src/components/standalone/dns_dhcp/CreateOrEditStaticLeaseDrawer.vue

Ensure that when creating a DHCP static lease, the MAC address is saved using colon syntax, not dash syntax.
Ref:
- https://github.com/NethServer/nethsecurity/issues/847

fix(dhcp): ensure MAC is saved with columns syntax

---

package-lock.json
package.json
public/i18n/en/translation.json
src/components/standalone/certificates/CertificatesTable.vue
tailwind.config.js

- Make **System > Certificates** table sortable
- Minor style fixes to certificates table
Related PR:
- https://github.com/nethesis/vue-components/pull/76

fix: make certificates table sortable

---

src/components/standalone/users_objects/CreateOrEditDomainSetDrawer.vue
src/i18n/en/translation.json

Lower to 960 the maximum characters of the domains of a domain set to avoid dnsmask crash
Ref:
- https://github.com/NethServer/nethsecurity/issues/877

fix: improve domain sets validation

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
src/i18n/en/translation.json

Ref:
- https://github.com/NethServer/nethsecurity/issues/879

fix(openvpn): adding server-side validation

---

src/i18n/en/translation.json

In #417 we've removed the locale specification, forgot to rename translation strings.

fix(lang): fixing translation fields under "languages"

---

src/components/standalone/users_objects/CreateOrEditDomainSetDrawer.vue
src/i18n/en/translation.json

The validation of the maximum characters used by a domain set in the dnsmasq configuration file is now handled on the backend.
Refs:
- https://github.com/NethServer/nethsecurity/issues/877
- https://github.com/NethServer/python3-nethsec/pull/73

fix: remove some validations for domain sets

---

src/components/controller/users/UsersTable.vue
src/components/standalone/monitoring/ConnectivityMonitor.vue
src/components/standalone/monitoring/connectivity/WanConnectionsCard.vue
src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue
src/composables/useNetworkDevices.ts
src/composables/useUciNetworkConfig.ts
src/i18n/en/translation.json
src/lib/standalone/network.ts
src/views/standalone/network/InterfacesAndDevicesView.vue

- Show IP addresses of wan interfaces in **Monitoring > Real time monitor > Connectivity**
- Make **WANs** card visible regardless of multiwan configuration status
- Introduce `useNetworkDevices` and `useUciNetworkConfig` composables
- Minor refactoring of `InterfacesAndDevicesView.vue`
- Move some utility functions to `network.ts`
- Enhance **Connectivity** page layout for very large screens
Ref:
- https://github.com/NethServer/nethsecurity/issues/890

feat(monitoring): show ip addresses of wan ifaces

---

src/components/standalone/monitoring/connectivity/WanConnectionsCard.vue
src/components/standalone/qos/CreateOrEditQoSInterfaceDrawer.vue

- Monitoring: show QoS status and assigned bandwidths of wan interfaces in **Monitoring > Real time monitor > Connectivity**
- QoS: Fix behavior of **Enabled** toggle
Ref:
- https://github.com/NethServer/nethsecurity/issues/890

feat(monitoring): show qos info of wan ifaces

---

src/components/charts/BasicBarChart.vue
src/components/charts/BasicPieChart.vue
src/components/charts/TimeLineChart.vue
src/components/standalone/monitoring/ConnectivityMonitor.vue
src/composables/useLatencyAndQualityReport.ts
src/i18n/en/translation.json

- Show latency and ping delivery rate charts under **Monitoring > Real time monitor > Connectivity**
- Add `TimeLineChart`, a reusable component for line charts having time on the x axis
- Improve description of **Ping latency monitor** page
- Add default values for `BasicBarChart` and `BasicPieChart` optional props
Ref:
- https://github.com/NethServer/nethsecurity/issues/904

feat(monitoring): add latency & ping delivery rate charts

---

src/components/standalone/monitoring/ConnectivityMonitor.vue
src/components/standalone/monitoring/connectivity/WanConnectionsCard.vue
src/i18n/en/translation.json
src/lib/standalone/network.ts

- Monitoring: show public IP address(es) of wan interfaces in **Monitoring > Real time monitor > Connectivity**
Ref:
- https://github.com/NethServer/nethsecurity/issues/890

fix(monitoring): show wan public ip address

---

src/components/charts/TimeLineChart.vue
src/components/standalone/monitoring/ConnectivityMonitor.vue

- Set the maximum value of the y-axis for the ping delivery rate to "100%"
- Enhance the configurability of `TimeLineChart` by introducing an `options` prop
Ref:
- https://github.com/NethServer/nethsecurity/issues/904

fix(monitoring): fix y scale of ping delivery rate

---

src/components/standalone/account/two_fa/TwoFactorAuth.vue
src/stores/controller/controllerLogin.ts

Fixing issue arisen with controller 1.2.0.
If no 2FA is configured), the controller doesn't save any info regarding the login. This causes issues due to the UI being unable to login into unit.
A workaround is to activate the 2FA and then logout and log back in.
Ref:
- https://mattermost.nethesis.it/nethesis/pl/rwak4t446pyqmfq1ark1taa5qh

fix(controller): fixing missed save of credentials

---

src/components/standalone/monitoring/InstantTrafficMonitor.vue
src/components/standalone/monitoring/TrafficMonitor.vue
src/components/standalone/monitoring/traffic/InstantAppTrafficCard.vue
src/components/standalone/monitoring/traffic/InstantHostTrafficCard.vue
src/components/standalone/monitoring/traffic/InstantProtocolTrafficCard.vue
src/composables/useTopTalkers.ts
src/views/standalone/monitoring/RealTimeMonitoringView.vue

Closes: https://github.com/NethServer/nethsecurity/issues/936
--- 
Screenshots:

refactor(traffic): moving instant traffic to another section

---

src/i18n/en/translation.json
src/lib/validation.ts
src/views/standalone/system/ControllerView.vue

Ref:
- https://github.com/NethServer/nethsecurity/issues/952

fix(controller): adding space as non-valid character

---

package.json

Due to incoming changes for monitoring, the API must be bumped to `2.1.0`.
Ref:
- https://github.com/NethServer/nethsecurity/pull/971

fix(controller): bump ns-api requirements

---

src/components/standalone/firewall/rules/CreateOrEditFirewallRuleDrawer.vue
src/components/standalone/firewall/rules/FirewallRulesTable.vue
src/i18n/en/translation.json
src/stores/standalone/firewall.ts

Introduce a true_zone property to the FirewallRule interface, improve display logic to account for zone existence, and add new translations for inactive and disabled firewall rules.
https://github.com/NethServer/nethsecurity/issues/899
https://github.com/user-attachments/assets/463d96b5-78b1-4184-bf6c-61302b7d64f9
https://github.com/user-attachments/assets/f6fd4ac7-e271-4161-a8af-ab6d86b16945

feat(firewall rule): highlight rules on non-existent zones

---

src/i18n/en/translation.json

fix a typo in english translation "block_dos_description"

fix EN "block_dos_description"

---

src/components/standalone/firewall/PortForwardTable.vue
src/i18n/en/translation.json

Introduce a tooltip for inactive port forwards when the header contains a hyphen and add translations for the inactive status and range object compatibility.
https://github.com/NethServer/nethsecurity/issues/898
if I revert the host range
Note:
it seems we need to save the upper unsaved change button if we want the change is effective

fix(port forward): adding tooltip for disabled port forwards

---

src/components/standalone/firewall/PortForwardTable.vue
src/i18n/en/translation.json

Reverts NethServer/nethsecurity-ui#482
To avoid such scenario, we need to improve the validation of objects.
See:
- https://github.com/NethServer/nethsecurity/issues/898
- https://github.com/NethServer/nethsecurity/issues/1032

fix(port forward): removing tooltip for disabled port forwards

---

src/components/standalone/ssh/SshKeys.vue
src/i18n/en/translation.json

Including changes coming from https://github.com/NethServer/nethsecurity/pull/1045

refactor(ssh): removing old api calls

---

src/components/standalone/security/threat_shield_dns/SettingsPanel.vue
src/stores/standalone/threatShield.ts

Load Threat shield DNS zones from `ns.threatshield dns-list-zones`
Ref:
- https://github.com/NethServer/nethsecurity/issues/906
- https://github.com/NethServer/nethsecurity/pull/1056

fix(threat shield): load ts dns zones from api

---

src/components/standalone/security/threat_shield/BlocklistTable.vue
src/stores/standalone/threatShield.ts

Changes:
- enterprise blocklist are listed on top, other lists are sorted by confidence
- if the translation language is not set, make sure to display the original description from API
Output example:
NethServer/nethsecurity#906

fix(ts-dns): improve blocklist table output

---

src/i18n/en/translation.json

Example screenshot:
Ref:
- https://github.com/NethServer/nethsecurity/issues/1089

fix: adding error for DHCP overlap

---

src/components/standalone/monitoring/ConnectivityMonitor.vue
src/components/standalone/monitoring/connectivity/WanConnectionsCard.vue
src/i18n/en/translation.json

Changes:
- always display all WANs
- retrieve the status from mwan: an installation with multiple WANs but without mwan configured is not good
mwan not configured:
mwan configured: second wan is in disabled state but remapped to "offline"
NethServer/nethsecurity#1148

fix(monitoring): improve IP field retrieval

---

src/components/standalone/dns_dhcp/LeasesTable.vue

Implement sorting capabilities for the leases table, allowing users to sort by various fields such as hostname, reservation, interface, address, and expiration. This enhances the user experience by providing better data organization.
To improve readability and alignment,  this `reservation name` field has been moved to the last column. This also aligns with its position in the drawer.
Refs: 
- https://github.com/NethServer/nethsecurity/issues/1087
- https://github.com/NethServer/nethsecurity/issues/1086
https://github.com/user-attachments/assets/2e527627-95a4-490b-af74-e93335490e0d

feat(dhcp-lease): sorting functionality, column reordering

---

src/components/standalone/ssh/SshConfig.vue
src/i18n/en/translation.json

Make sure to configure the SSH server named main.
Otherwise when the HA is configured, the UI will show and configure dropbear instance dedicated to the HA.
Split from #533 
Companion PR: https://github.com/NethServer/nethsecurity/pull/871
Main issue: NethServer/nethsecurity#920

fix(ssh): configure only main dropbear server

---

src/components/standalone/dns_dhcp/LeasesTable.vue

The reservation_name was using the wrong key for sorting.
NethServer/nethsecurity#1087

fix(dhcp): correct reservation name sorting

---

src/components/standalone/firewall/nat/CreateOrEditNatRuleDrawer.vue
src/components/standalone/firewall/nat/NatRulesTable.vue
src/i18n/en/translation.json
src/stores/standalone/firewall.ts

Needs: https://github.com/NethServer/nethsecurity/pull/1235
Closes https://github.com/NethServer/nethsecurity/issues/1183

feat(nat): added device specification for NATs

---

src/components/standalone/dashboard/SystemInfoCard.vue

If the storage is configured but the usage is 0, the bar doesn't come up on the dashboard.

fix(dashboard): fixed storage usage bar if is zero

---

src/components/standalone/dpi/CreateOrDeleteDpiExceptionDrawer.vue

Tool supported the feature, but was blocked the insertion from the UI

fix(dpi): allowed insertion of CIDRs in exceptions

---

src/components/standalone/security/FlashstartContent.vue
src/i18n/en/translation.json

Due to dnsmasq configuration, prompt flashstart users to set DNS manually.
Closes: https://github.com/NethServer/nethsecurity/issues/1162

fix: added info message for DNS setting

---

src/i18n/it/translation.json

The Italian label was using the wrong placeholder, so the date was not shown.
See https://partner.nethesis.it/t/aggiunta-informazioni-schedulazione-upgrade-nethsecurity/9495

fix(controller): correct Italian translation

---

src/components/standalone/security/threat_shield_dns/AllowedDomainsTable.vue
src/components/standalone/security/threat_shield_dns/CreateOrEditAllowedDomainDrawer.vue
src/components/standalone/security/threat_shield_dns/CreateOrEditBlockedDomainDrawer.vue
src/components/standalone/security/threat_shield_dns/FilterBypassPanel.vue
src/components/standalone/security/threat_shield_dns/LocalAllowlistPanel.vue
src/components/standalone/security/threat_shield_dns/LocalBlocklistPanel.vue
src/i18n/en/translation.json
src/stores/standalone/threatShield.ts
src/views/standalone/security/ThreatShieldDnsView.vue

Closes ~~NethServer/nethsecurity#1327~~ https://github.com/NethServer/nethsecurity/issues/1221
Allow CRUD actions on Adblock local allow list
Empty state:
List:
Add:
Edit:
Delete:

feat(ts_dns): add local allowlist

---

src/components/controller/users/CreateOrEditUserDrawer.vue

Previously, the edit drawer of users was not showing the selected unit groups for a user.
NethServer/nethsecurity#1300

fix(controller): show selected unit groups

---

src/components/controller/unit_groups/CreateOrEditUnitGroupDrawer.vue
src/components/controller/units/RemoveUnitModal.vue
src/components/controller/units/UnitsTable.vue
src/components/controller/users/CreateOrEditUserDrawer.vue
src/i18n/en/translation.json

**Unit and Unit Group Management Improvements:**
* Made the selection of units optional when creating or editing a unit group by removing the validation requirement and explicitly marking the field as optional in the UI (`CreateOrEditUnitGroupDrawer.vue`) [[1]](diffhunk://#diff-b4044a64e0888c9d2f0a8038e3d7da60342ba9fc7c85e5624770e1dea83542f3L89-L92) [[2]](diffhunk://#diff-b4044a64e0888c9d2f0a8038e3d7da60342ba9fc7c85e5624770e1dea83542f3R191).
* Updated user group selection for users to be explicitly optional in the UI (`CreateOrEditUserDrawer.vue`).
**Unit Removal Flow Enhancements:**
* Changed the logic so that units belonging to groups can now be removed directly, and added a message to inform users that the unit will also be removed from its groups (`UnitsTable.vue`, …

fix(controller): minor UI improvements

---

src/components/standalone/openvpn_tunnel/CreateOrEditTunnelDrawer.vue

Change from `lz0` to `lzo`: the `lz0` does not exists.
The algorithm is correct for OpenVPN road warrior.
NethServer/nethsecurity#1357

fix(ovpn tunnel): change compression alg id

---

src/components/standalone/firewall/CreateOrEditPortForwardDrawer.vue

Make sure the destination IP is always validated,
even if the destination port is set.
Fix NethServer/nethsecurity#1363

fix(redirects): better destination IP validation

---

src/components/standalone/dns_dhcp/LeasesTable.vue

Spotted an issue where reactivity was not triggering correctly by using non-reactive prop as reactive

fix(dhcp): fixed reactivity for filtering
